/**
 * sites/ctrader-auth-site/build.js
 *
 * Optional build-time config generator. When run inside Appwrite's build
 * environment, it overwrites config.js with values from environment variables.
 * If no env vars are set, the committed defaults are left intact.
 */

const fs = require('fs');
const path = require('path');

const defaults = {
  endpoint: 'https://sgp.cloud.appwrite.io/v1',
  projectId: '6a22a362002b9ae880bb',
  authFunctionUrl: 'https://auth.mrme.tech',
  pinFunctionUrl: 'https://pin.mrme.tech',
  internalFunctionUrl: 'https://internal.mrme.tech',
  siteUrl: 'https://app.mrme.tech',
};

const config = {
  endpoint: process.env.APPWRITE_ENDPOINT || defaults.endpoint,
  projectId: process.env.APPWRITE_PROJECT_ID || defaults.projectId,
  authFunctionUrl: process.env.AUTH_FUNCTION_URL || defaults.authFunctionUrl,
  pinFunctionUrl: process.env.PIN_FUNCTION_URL || defaults.pinFunctionUrl,
  internalFunctionUrl: process.env.INTERNAL_FUNCTION_URL || defaults.internalFunctionUrl,
  siteUrl: process.env.SITE_URL || defaults.siteUrl,
};

const out = `/**
 * Site configuration — deployed URLs
 *
 * Generated by build.js from environment variables. The committed defaults
 * are used when no env vars are present, so local file:// testing still works.
 */
window.APP_CONFIG = ${JSON.stringify(config, null, 2)};
`;

const target = path.join(__dirname, 'config.js');
fs.writeFileSync(target, out, 'utf8');
console.log(`[build] wrote ${target}`);
