/**
 * sites/ctrader-command-center/build.js
 *
 * Build-time config generator for the command center. When run inside
 * Appwrite's build environment, it overwrites config.js with values from
 * environment variables. If no env vars are set, committed defaults stay.
 */

const fs = require('fs');
const path = require('path');

const defaults = {
  appwriteEndpoint: 'https://sgp.cloud.appwrite.io/v1',
  appwriteProjectId: '6a22a362002b9ae880bb',
  authSessionUrl: 'https://auth.mrme.tech/session',
  v2ApiBase: 'https://ssfx-api.mrme.tech',
  dataserviceBase: 'https://dataservice.mrme.tech',
  adminApiKey: '',
  databaseId: '6a44553f0034baa503c8',
  accountsTable: 'ssfx_accounts',
  presetsTable: 'ssfx_presets',
};

const config = {
  appwriteEndpoint: process.env.APPWRITE_ENDPOINT || defaults.appwriteEndpoint,
  appwriteProjectId: process.env.APPWRITE_PROJECT_ID || defaults.appwriteProjectId,
  authSessionUrl: process.env.AUTH_SESSION_URL || defaults.authSessionUrl,
  v2ApiBase: process.env.V2_API_BASE || defaults.v2ApiBase,
  dataserviceBase: process.env.DATASERVICE_BASE || defaults.dataserviceBase,
  adminApiKey: process.env.ADMIN_API_KEY || defaults.adminApiKey,
  databaseId: process.env.DATABASE_ID || defaults.databaseId,
  accountsTable: process.env.ACCOUNTS_TABLE || defaults.accountsTable,
  presetsTable: process.env.PRESETS_TABLE || defaults.presetsTable,
};

const out = `/**
 * Command Center configuration — deployed URLs
 *
 * Generated by build.js from environment variables. The committed defaults
 * are used when no env vars are present, so local file:// testing still works.
 */
window.APP_CONFIG = ${JSON.stringify(config, null, 2)};
`;

const target = path.join(__dirname, 'config.js');
fs.writeFileSync(target, out, 'utf8');
console.log(`[build] wrote ${target}`);
