/**
 * sites/ssfx-hq/build.js
 * Build-time config generator. Overwrites config.js with env vars when run inside Appwrite build.
 */

const fs = require('fs');
const path = require('path');

const defaults = {
  endpoint: 'https://sgp.cloud.appwrite.io/v1',
  projectId: '6a22a362002b9ae880bb',
  authDomain: 'https://auth.mrme.tech',
  pinDomain: 'https://pin.mrme.tech',
  v2ApiBase: 'https://ssfx-api.mrme.tech',
  dataserviceBase: 'https://dataservice.mrme.tech',
  agentHarnessBase: 'https://agent.mrme.tech',
  databaseId: 'ctrader_auth',
  marketDatabaseId: 'market_data',
  siteUrl: 'https://app.mrme.tech',
  v2AdminKey: '',
  dataserviceApiKey: '',
};

// Map of config keys to additional environment variable names to try
const envKeyAliases = {
  dataserviceApiKey: ['DATA_SERVICE_API_KEY', 'DATASERVICE_API_KEY'],
  v2AdminKey: ['V2_ADMIN_KEY', 'ADMIN_API_KEY', 'V2ADMIN_KEY'],
  agentHarnessBase: ['AGENT_HARNESS_BASE'],
};

const config = {};
for (const [k, v] of Object.entries(defaults)) {
  // Try camelCase version first
  const camelKey = k.toUpperCase();
  
  // Try environment variable aliases (e.g., V2_ADMIN_KEY, DATA_SERVICE_API_KEY)
  const aliases = envKeyAliases[k] || [];
  
  // Build list of env var names to try: camelCase, snake_case, and aliases
  const envKeys = [camelKey];
  
  // Convert camelCase to UPPER_SNAKE_CASE (e.g., v2AdminKey -> V2_ADMIN_KEY)
  const snakeKey = k.replace(/([A-Z])/g, (match, p1, offset) => {
    return offset > 0 ? '_' + p1 : p1;
  }).toUpperCase();
  envKeys.push(snakeKey);
  
  // Add any aliases
  envKeys.push(...aliases);
  
  // Find the first matching environment variable
  let value = v;
  for (const envKey of envKeys) {
    if (process.env[envKey]) {
      value = process.env[envKey];
      break;
    }
  }
  config[k] = value;
}

const out = `/**\n * SSFX HQ — consolidated command platform configuration\n * Generated by build.js from environment variables.\n */\nwindow.APP_CONFIG = ${JSON.stringify(config, null, 2)};\n`;

const target = path.join(__dirname, 'config.js');
fs.writeFileSync(target, out, 'utf8');
console.log(`[build] wrote ${target}`);
