/**
 * sites/ssfx-hq/build.js
 * Build-time config generator. Overwrites config.js with env vars when run inside Appwrite build.
 */

const fs = require('fs');
const path = require('path');

const defaults = {
  endpoint: 'https://sgp.cloud.appwrite.io/v1',
  projectId: '6a22a362002b9ae880bb',
  authDomain: 'https://auth.mrme.tech',
  pinDomain: 'https://pin.mrme.tech',
  v2ApiBase: 'https://ssfx-api.mrme.tech',
  dataserviceBase: 'https://dataservice.mrme.tech',
  agentHarnessBase: 'https://agent.mrme.tech',
  databaseId: 'ctrader_auth',
  marketDatabaseId: 'market_data',
  siteUrl: 'https://app.mrme.tech',
  v2AdminKey: '',
  dataserviceApiKey: '',
};

const config = {};
for (const [k, v] of Object.entries(defaults)) {
  const envKey = k.toUpperCase();
  config[k] = process.env[envKey] || v;
}

const out = `/**\n * SSFX HQ — consolidated command platform configuration\n * Generated by build.js from environment variables.\n */\nwindow.APP_CONFIG = ${JSON.stringify(config, null, 2)};\n`;

const target = path.join(__dirname, 'config.js');
fs.writeFileSync(target, out, 'utf8');
console.log(`[build] wrote ${target}`);
