/**
 * SSFX HQ — consolidated command platform configuration
 * Generated by build.js from environment variables.
 */
window.APP_CONFIG = {
  "endpoint": "https://sgp.cloud.appwrite.io/v1",
  "projectId": "6a22a362002b9ae880bb",
  "authDomain": "https://auth.mrme.tech",
  "pinDomain": "https://auth.mrme.tech",
  "apiBase": "https://api.mrme.tech",
  "v2ApiBase": "https://api.mrme.tech",
  "marketBase": "https://market.mrme.tech",
  "dataserviceBase": "https://market.mrme.tech",
  "aiBase": "https://ai.mrme.tech",
  "agentHarnessBase": "https://ai.mrme.tech",
  "researchBase": "https://research.mrme.tech",
  "pplxAgentBase": "https://research.mrme.tech",
  "databaseId": "slwp_platform",
  "marketDatabaseId": "market_data",
  "siteUrl": "https://app.mrme.tech",
  "adminKey": "",
  "v2AdminKey": "",
  "marketApiKey": "",
  "dataserviceApiKey": ""
};
