/**
 * SSFX HQ — consolidated command platform configuration
 * Generated by build.js from environment variables.
 */
window.APP_CONFIG = {
  "endpoint": "https://sgp.cloud.appwrite.io/v1",
  "projectId": "6a22a362002b9ae880bb",
  "authDomain": "https://auth.mrme.tech",
  "pinDomain": "https://pin.mrme.tech",
  "v2ApiBase": "https://ssfx-api.mrme.tech",
  "dataserviceBase": "https://dataservice.mrme.tech",
  "agentHarnessBase": "https://agent.mrme.tech",
  "databaseId": "ctrader_auth",
  "marketDatabaseId": "market_data",
  "siteUrl": "https://app.mrme.tech",
  "v2AdminKey": "my-admin-key",
  "dataserviceApiKey": "my-ds-key"
};
