"""Storage protocols for signals and account state."""
from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any, Protocol

from ssfx_parser import RawMessage, SlaveExecution, TradeSignal


class SignalStore(Protocol):
    def save_raw_message(self, msg: RawMessage) -> bool: ...
    def get_today_messages(self, chat_id: str | None = None) -> list[RawMessage]: ...
    def save_signal(self, signal: TradeSignal) -> bool: ...
    def get_signal(self, chat_id: str, message_id: int) -> TradeSignal | None: ...
    def get_active_signals(self, chat_id: str | None = None) -> list[TradeSignal]: ...
    def get_pending_entry_signals(self) -> list[TradeSignal]: ...
    def update_signal_status(
        self,
        chat_id: str,
        message_id: int,
        status: str,
        order_id: int | None = None,
        position_id: int | None = None,
        executed_price: float | None = None,
        error: str | None = None,
        volume: float | None = None,
    ) -> None: ...
    def update_signal_entry(self, chat_id: str, message_id: int, entry_price: float) -> None: ...
    def record_trade(self, signal: TradeSignal, result: dict[str, Any]) -> None: ...
    def list_signals(self, limit: int = 50) -> list[TradeSignal]: ...
    def list_trades(self, limit: int = 50) -> list[dict[str, Any]]: ...
    def watch_signals(self) -> AsyncIterator[TradeSignal]: ...


class AccountStore(Protocol):
    def list_accounts(self, owner_id: str | None = None) -> list[Any]: ...
    def get_account(self, name: str, owner_id: str | None = None) -> Any | None: ...
    def save_account(self, account: Any) -> None: ...
    def has_execution(self, slave_id: str, chat_id: str, message_id: int) -> bool: ...
    def get_execution(self, slave_id: str, chat_id: str, message_id: int) -> SlaveExecution | None: ...
    def update_execution(
        self,
        slave_id: str,
        chat_id: str,
        message_id: int,
        signal_type: str,
        status: str,
        order_id: int | None = None,
        position_id: int | None = None,
        executed_price: float | None = None,
        volume: float | None = None,
        original_volume_lots: float | None = None,
        error: str | None = None,
        skip_reason: str | None = None,
    ) -> None: ...
    def mark_skipped(self, slave_id: str, chat_id: str, message_id: int, reason: str) -> None: ...
    def get_active_executions(self, slave_id: str) -> list[SlaveExecution]: ...
    def list_recent_executions(self, slave_id: str, limit: int = 50) -> list[SlaveExecution]: ...
    # Risk-state persistence for kill-switches
    def get_risk_state(
        self, account_name: str, date_str: str
    ) -> dict[str, Any] | None: ...
    def upsert_risk_state(
        self, account_name: str, state: dict[str, Any]
    ) -> None: ...
