"""Execution backend protocol — abstracts cTrader/simulated/paper trading."""
from __future__ import annotations

from typing import Any, Protocol

from ssfx_parser import TradeSignal


class ExecutionBackend(Protocol):
    """Pluggable backend for order execution and account queries."""

    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def get_account_summary(self) -> dict[str, float]: ...
    async def open_position(
        self, signal: TradeSignal, volume_lots: float
    ) -> dict[str, Any]: ...
    async def close_position(self, position_id: int, volume_lots: float | None) -> dict[str, Any]: ...
    async def amend_position_sltp(
        self, position_id: int, stop_loss: float | None, take_profit: float | None
    ) -> dict[str, Any]: ...
    async def cancel_order(self, order_id: int) -> dict[str, Any]: ...
    async def get_open_position_ids(self) -> set[int]: ...
