name = "ssfx-callback-proxy"
main = "src/index.js"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "ssfx-callback-proxy"

[env.staging]
name = "ssfx-callback-proxy-staging"
